version: '3'
services:
  delugevpn:
    container_name: delugevpn
    image: binhex/arch-delugevpn
    cap_add: 
      - NET_ADMIN
    ports: 
      - '8112:8112'
      - '8118:8118'
      - '58846:58846'
      - '58946:58946'
    depends_on:
      - nginx
    volumes:
      - ${DOWNLOAD_PATH}:/downloads
      - ${CONFIG_PATH}/delugevpn:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    env_file:
      - delugevpn.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  nginx:
    container_name: nginx
    image: linuxserver/letsencrypt
    cap_add: 
      - NET_ADMIN
    ports:
      - '443:443'
      - '80:80'
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ${CONFIG_PATH}/letsencrypt:/config
     - ${CONFIG_PATH}/organizr:/database
    restart: always
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=${NGINX_EMAIL}
      - URL=${NGINX_URL}
      - VALIDATION=${NGINX_VALIDATION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  plex:
    container_name: plex
    image: plexinc/pms-docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/plex/config:/config
      - ${CONFIG_PATH}/plex/transcode:/transcode
      - ${DATA_PATH}:/data
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: always
    hostname: master
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    depends_on:
      - delugevpn
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${TV_PATH}:/tv
      - ${DOWNLOAD_PATH}:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    depends_on:
      - delugevpn
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOAD_PATH}:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy
      
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_PATH}/jackett:/config
      - ${DOWNLOAD_PATH}:/downloads
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  ombi:
    container_name: ombi
    image: linuxserver/ombi
    ports:
      - '3579:3579'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/ombi:/config
    environment:
      - HOME=/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - '9000:9000'
    environment:
      - HTTPS_PROXY=${PORTAINER_HTTPS_PROXY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart:
      always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy
      
  glances:
    image: docker.io/nicolargo/glances
    container_name: glances
    ports:
      - "61208-61209:61208-61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    pid: "host"
    restart:
      always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - proxy
  
networks:
  proxy:
